var string1 = "consumertobusinessdeploymentviralitycrowdfundingsocialmediabandwidthacceleratorbusinessdisruptivestartupcrowdsourcelaunchpartybuyeralphaiterationproductmanagementagiledevelopmentpartnershipdirectmail";
var string2 = "ingadvisorchannelstechnologyfirstmoveradvantagevalidationbetauserexperienceangelinvestorseedroundparadigmshiftsalespartnershipcrowdfundingpartnernetworkchannelsleanstartupseedmoneyventurepivothackath";
var string3 = "onpartnershipreleaseleanstartupventureleveragegrowthhackingchurnratebootstrappingchannelsdirectmailingseriesAfinancingagiledevelopmentadvisorseedmoneyviralityuserexperiencebusinessmodelcanvasmassmark";
var string4 = "etvalidationconversionanalyticsplaninteractiondesigncrowdsourcemassmarketnichemarketstocktestingstrategyvaluepropositionfoundersleverageviralitybrandingventurechurnratelongtailmetricsearlyadoptersbac";
var string5 = "kingfirstmoveradvantageproductmanagementseriesAfinancingsocialmediaagiledevelopmentdisruptivemarketinguserinterfaceratestartupassetshypothesesgendisruptivefirstmoveradvantagedirectmailinghandshakenet";
var string6 = "workeffectsvalidationmarketingdeploymentstartupagiledevelopmentinfographicalphamonetizationleveragestockcustomermarketingfundingstockinfluencerparadigmshiftsocialproofproductmanagementlearningcurveex";
var string7 = "periencedirectmailingmetricsbusinessplansocialmediaadvisordeploymentownershipbootstrappingbuzzinfrastructuresalesearlyadoptersfocuslearningcurvemassmarketangelinvestorinfluencercrowdsourcemarketmetri";
var string8 = "csviralityresponsivewebdesignecosystemcrowdsourcebuyerinfrastructuregamificationvestingperiodbuzzrockstarseedmoneybuyerstockhackathonclientmassmarketbusinessplanownershipbuyerincubatorcrowdfundingfre";
var string9 = "emiumresponsivewebdesignstartupfoundersleanstartupsocialproofanalyticsbrandingbusinessincubatorhypothesesstockhandshakeentrepreneurhypothesesbrandingagiledevelopmentresearchanddevelopmentfocusearlyad";
var string10 = "optersscrumprojectbetatermsheetvalidationvaluepropositionfundingstealthstartupstockpitchparadigmshiftalphastrategyventurenichemarketassetsadvisordeploymentchannelshypothesesstockholygrailstealthboots";
var string11 = "trapingmonetization";
if (window.location.href  === "http://localhost/adpage/ads.html") {
  window.history.pushState("string", "Title", "http://localhost/adpage/ads.html?" + string1 + string2 + string3 + string4 + string5 + string6 + string7 + string8 + string9  + string10 + string11);
}
